// Product data for Inkphyous e-commerce
// Images are served from /products/ directory

const products = [
  {
    id: 1,
    name: "Jersey Reptile",
    nameAr: "جيرسي الزواحف",
    brand: "Inkphyous",
    category: "Jerseys",
    subcategory: "Streetwear",
    image: "/products/JR1_Black.png",
    summary: "Oversized unisex jersey with 00 Reptile prints and signature embroidery.",
    summaryAr: "جيرسي للجنسين بقصة واسعة مع طبعات زواحف 00 وتطريز مميز.",
    description: `The Jersey "Reptile" is crafted from 100% dry-fit polyester jersey, offering a smooth, structured hand feel. Designed in an oversized unisex silhouette with a ribbed neckline, it features Reptile graphics on the front and back, complemented by logo embroidery on sleeves and signature embroidery at the front and back.`,
    descriptionAr: `جيرسي "الزواحف" مصنوع من بوليستر دراي فيت بنسبة 100%، مما يوفر ملمسًا ناعمًا ومنظمًا. مصمم بقصة واسعة للجنسين مع ياقة مضلعة، ويتميز برسومات الزواحف من الأمام والخلف، بالإضافة إلى تطريز الشعار على الأكمام وتطريز مميز من الأمام والخلف.`,
    priceINR: 2499,
    discountPriceINR: 1945,
    sizeOptions: ["S", "M", "L", "XL"],
    color: "Black",
    availableColors: ["Black", "Pink", "Grey"],
    details: {
      fabric: "100% Polyester - Dry Fit",
      washCare: "Machine wash cold, air dry",
      fit: "Oversized Fit",
      features: "Screenprinted back, Graphics and embroidery front/back, Patches on sleeves, Ribbed neckline",
    },
    detailsAr: {
      fabric: "100% بوليستر - دراي فيت",
      washCare: "غسيل آلي بالماء البارد، تجفيف بالهواء",
      fit: "قصة واسعة",
      features: "طباعة شاشة في الخلف، رسومات وتطريز من الأمام/الخلف، رقع على الأكمام، ياقة مضلعة",
    },
    variants: [
      {
        id: "JSY-2025-RPT-BLK-M",
        name: "Jersey Lizard",
        color: "Black",
        priceINR: 1945,
        image: "/products/JR1_Black.png",
        images: [
          "/products/JR1_Black_1.jpeg",
          "/products/JR1_Black_2.jpeg",
          "/products/JR1_Black_3.jpeg",
          "/products/JR1_Black_4.jpeg",
          "/products/JR1_Black_5.jpeg",
          "/products/JR1_Black_6.jpeg",
        ],
      },
      {
        id: "JSY-2025-RPT-PNK-L",
        name: "Jersey Snake",
        color: "Pink",
        priceINR: 1945,
        image: "/products/JR1_Pink.png",
        images: [
          "/products/JR1_Pink_1.jpeg",
          "/products/JR1_Pink_2.jpeg",
          "/products/JR1_Pink_3.jpeg",
          "/products/JR1_Pink_4.jpeg",
          "/products/JR1_Pink_5.jpeg",
          "/products/JR1_Pink_6.jpeg",
        ],
      },
      {
        id: "JSY-2025-RPT-GRY-XL",
        name: "Jersey Frog",
        color: "Grey",
        priceINR: 1945,
        image: "/products/JR1_Grey.png",
        images: [
          "/products/JR1_Grey_1.jpeg",
          "/products/JR1_Grey_2.jpeg",
          "/products/JR1_Grey_3.jpeg",
          "/products/JR1_Grey_4.jpeg",
          "/products/JR1_Grey_5.jpeg",
        ],
      },
    ],
    rating: 4.5,
    reviews: 88,
  },
  {
    id: 2,
    name: "Jersey Elements",
    nameAr: "جيرسي العناصر",
    brand: "Inkphyous",
    category: "Jerseys",
    subcategory: "Streetwear",
    image: "/products/JE1_Green.png",
    summary: "Oversized unisex jersey with 00 Element prints and signature embroidery.",
    summaryAr: "جيرسي للجنسين بقصة واسعة مع طبعات عناصر 00 وتطريز مميز.",
    description: `The Jersey "Elements" is crafted from 100% dry-fit polyester jersey, offering a smooth, refined hand feel. Designed in an oversized unisex silhouette with a ribbed neckline, it features Elements graphics and screenprints on the front and back.`,
    descriptionAr: `جيرسي "العناصر" مصنوع من بوليستر دراي فيت بنسبة 100%، مما يوفر ملمسًا ناعمًا وراقيًا. مصمم بقصة واسعة للجنسين مع ياقة مضلعة، ويتميز برسومات وطبعات شاشة للعناصر من الأمام والخلف.`,
    priceINR: 2399,
    discountPriceINR: 1945,
    sizeOptions: ["S", "M", "L", "XL"],
    color: "Green",
    availableColors: ["Green", "White", "Blue"],
    details: {
      fabric: "100% Polyester - Dry Fit",
      washCare: "Machine wash cold, air dry",
      fit: "Oversized Fit",
      features: "Screenprinted front/back/sleeves, Lining design on sleeves, Logo embroidery, Patches on shoulders",
    },
    detailsAr: {
      fabric: "100% بوليستر - دراي فيت",
      washCare: "غسيل آلي بالماء البارد، تجفيف بالهواء",
      fit: "قصة واسعة",
      features: "طباعة شاشة في الأمام/الخلف/الأكمام، تصميم مبطن على الأكمام، تطريز الشعار، رقع على الأكتاف",
    },
    variants: [
      {
        id: "JSY-2025-ELE-GRN-M",
        name: "Jersey Plant",
        color: "Green",
        priceINR: 1945,
        image: "/products/JE1_Green.png",
        images: [
          "/products/JE1_Green_1.jpeg",
          "/products/JE1_Green_2.jpeg",
          "/products/JE1_Green_3.jpeg",
          "/products/JE1_Green_4.JPG",
          "/products/JE1_Green_5.JPG",
        ],
      },
      {
        id: "JSY-2025-ELE-WHT-L",
        name: "Jersey Fire",
        color: "White",
        priceINR: 1945,
        image: "/products/JE1_White.png",
        images: [
          "/products/JE1_White_1.jpeg",
          "/products/JE1_White_2.jpeg",
          "/products/JE1_White_3.JPG",
          "/products/JE1_White_4.jpeg",
          "/products/JE1_White_5.jpeg",
        ],
      },
      {
        id: "JSY-2025-ELE-BLU-XL",
        name: "Jersey Wave",
        color: "Blue",
        priceINR: 1945,
        image: "/products/JE1_Blue.png",
        images: [
          "/products/JE1_Blue_1.jpeg",
          "/products/JE1_Blue_2.jpeg",
          "/products/JE1_Blue_3.jpeg",
          "/products/JE1_Blue_4.jpeg",
          "/products/JE1_Blue_5.JPG",
        ],
      },
    ],
    rating: 4.4,
    reviews: 76,
  },
  {
    id: 3,
    name: "Jersey Box Fitted",
    nameAr: "جيرسي بوكس فيت",
    brand: "Inkphyous",
    category: "Jerseys",
    subcategory: "Mesh",
    image: "/products/JB1_White.png",
    summary: "Boxy unisex mesh jersey with 00 & Inkphyous sublimation prints.",
    summaryAr: "جيرسي شبكي للجنسين بقصة مربعة مع طبعات 00 و Inkphyous.",
    description: `The Jersey "Boxy Fit Athletic Mesh" is crafted from 100% polyester mesh, offering a lightweight, breathable hand feel with a structured drape.`,
    descriptionAr: `جيرسي "الشبك الرياضي بقصة مربعة" مصنوع من شبك البوليستر بنسبة 100%، مما يوفر ملمسًا خفيف الوزن ومساميًا مع ثنية منظمة.`,
    priceINR: 2299,
    discountPriceINR: 1045,
    sizeOptions: ["S", "M", "L", "XL"],
    color: "White",
    availableColors: ["White", "Black"],
    details: {
      fabric: "100% Polyester - Mesh",
      washCare: "Machine wash cold, air dry",
      fit: "Boxy Oversized Fit",
      features: "Sublimation front/back, Ribbed neckline, Short sleeves",
    },
    detailsAr: {
      fabric: "100% بوليستر - شبك",
      washCare: "غسيل آلي بالماء البارد، تجفيف بالهواء",
      fit: "قصة مربعة واسعة",
      features: "طباعة تسامي في الأمام/الخلف، ياقة مضلعة، أكمام قصيرة",
    },
    variants: [
      {
        id: "JSY-2025-BOX-WHT-M",
        name: "Jersey Boxy Mesh White",
        color: "White",
        priceINR: 1045,
        image: "/products/JB1_White.png",
        images: [
          "/products/JB1_White_1.png",
          "/products/JB1_White_2.PNG",
          "/products/JB1_White_3.jpeg",
          "/products/JB1_White_4.JPG",
          "/products/JB1_White_5.JPG",
        ],
      },
      {
        id: "JSY-2025-BOX-BLK-L",
        name: "Jersey Boxy Mesh Black",
        color: "Black",
        priceINR: 1045,
        image: "/products/JB1_Black.png",
        images: [
          "/products/JB1_Black_1.jpeg",
          "/products/JB1_Black_2.jpeg",
          "/products/JB1_Black_3.JPG",
          "/products/JB1_Black_4.JPG",
          "/products/JB1_Black_5.JPG",
        ],
      },
    ],
    rating: 4.6,
    reviews: 70,
  },
  {
    id: 4,
    name: "Polyester Jhorts",
    nameAr: "شورت بوليستر",
    brand: "Inkphyous",
    category: "Shorts",
    subcategory: "Bottoms",
    image: "/products/JH1_White.png",
    summary: "Oversized unisex jorts with front screenprints and woven waist belt.",
    summaryAr: "شورت واسع للجنسين مع طبعات أمامية وحزام خصر منسوج.",
    description: `The Jorts "Relax Fit" are crafted from 100% polyester with a smooth, structured hand feel. Designed in an oversized unisex silhouette with a woven elastic waist belt and long drawstring.`,
    descriptionAr: `شورت "ريلاكس فيت" مصنوع من البوليستر بنسبة 100% مع ملمس ناعم ومنظم. مصمم بقصة واسعة للجنسين مع حزام خصر مرن منسوج ورباط طويل.`,
    priceINR: 1899,
    discountPriceINR: 1045,
    sizeOptions: ["S", "M", "L", "XL"],
    color: "White",
    availableColors: ["White", "Black"],
    details: {
      fabric: "100% Polyester - Diagonal Weave",
      washCare: "Machine wash cold, tumble dry low",
      fit: "Oversized Fit",
      features: "Below knee length, Screenprint front, HD print border, Elastic waist belt",
    },
    detailsAr: {
      fabric: "100% بوليستر - نسيج قطري",
      washCare: "غسيل آلي بالماء البارد، تجفيف بدرجة حرارة منخفضة",
      fit: "قصة واسعة",
      features: "طول تحت الركبة، طباعة شاشة في الأمام، حد طباعة HD، حزام خصر مرن",
    },
    variants: [
      {
        id: "JRT-2025-DIA-WHT-M",
        name: "Jhorts White",
        color: "White",
        priceINR: 1045,
        image: "/products/JH1_White.png",
        images: [
          "/products/JH1_White_1.jpeg",
          "/products/JH1_White_2.jpeg",
          "/products/JH1_White_3.JPG",
          "/products/JH1_White_4.JPG",
        ],
      },
      {
        id: "JRT-2025-DIA-BLK-L",
        name: "Jhorts Black",
        color: "Black",
        priceINR: 1045,
        image: "/products/JH1_Black.png",
        images: [
          "/products/JH1_Black_1.JPG",
          "/products/JH1_Black_2.JPG",
          "/products/JH1_Black_3.JPG",
          "/products/JH1_Black_4.png",
        ],
      },
    ],
    rating: 4.3,
    reviews: 65,
  },
  {
    id: 5,
    name: "Relax Trackpants",
    nameAr: "بنطال رياضي ريلاكس",
    brand: "Inkphyous",
    category: "Pants",
    subcategory: "Bottoms",
    image: "/products/RT1_White.png",
    summary: "Oversized unisex trackpants with front screenprints and woven waist belt.",
    summaryAr: "بنطال رياضي واسع للجنسين مع طبعات أمامية وحزام خصر منسوج.",
    description: `The Trackpants "Relax Fit" are crafted from 100% net and silky-soft polyester, offering a lightweight, smooth hand feel.`,
    descriptionAr: `بنطال "ريلاكس فيت" مصنوع من شبك وبوليستر ناعم بنسبة 100%، مما يوفر ملمسًا خفيف الوزن وناعمًا.`,
    priceINR: 2199,
    discountPriceINR: 1445,
    sizeOptions: ["S", "M", "L", "XL"],
    color: "White",
    availableColors: ["White", "Black"],
    details: {
      fabric: "100% Polyester - Net/Silky Soft",
      washCare: "Machine wash cold, air dry",
      fit: "Oversized Fit",
      features: "Full length, Screenprint front, Elastic waist belt",
    },
    detailsAr: {
      fabric: "100% بوليستر - شبك/ناعم",
      washCare: "غسيل آلي بالماء البارد، تجفيف بالهواء",
      fit: "قصة واسعة",
      features: "طول كامل، طباعة شاشة في الأمام، حزام خصر مرن",
    },
    variants: [
      {
        id: "TRK-2025-RLX-WHT-M",
        name: "Relax Tracks White",
        color: "White",
        priceINR: 1445,
        image: "/products/RT1_White.png",
        images: [
          "/products/RT1_White_1.JPG",
          "/products/RT1_White_2.JPG",
          "/products/RT1_White_3.JPG",
          "/products/RT1_White_4.JPG",
        ],
      },
      {
        id: "TRK-2025-RLX-BLK-L",
        name: "Relax Tracks Black",
        color: "Black",
        priceINR: 1445,
        image: "/products/RT1_Black.png",
        images: [
          "/products/RT1_Black_1.jpeg",
          "/products/RT1_Black_2.JPG",
          "/products/RT1_Black_3.JPG",
          "/products/RT1_Black_4.JPG",
        ],
      },
    ],
    rating: 4.5,
    reviews: 110,
  },
];

export default products;
